---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: "Include ansible-ubuntu-disable-auto-update"
      ansible.builtin.include_role:
        name: "ansible-ubuntu-disable-auto-update"
